GoTourSiteAdmin/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using GoTourSiteAdmin.Models;
using GoTourSiteAdmin.Services.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GoTourSiteAdmin.Controllers
{
    public class CityController : Controller {
        private ICityService _vCityService;
        private ILanguageService _vLanguageSerivce;
        #region Constructor
        public CityController(ICityService vCityService, ILanguageService vLanguageService) {
            _vCityService = vCityService;
            _vLanguageSerivce = vLanguageService;
        }
        #endregion
        public IActionResult All() {
            return View();
        }
        public IActionResult AddCity() {
            return View();
        }
        public async Task<IActionResult> EditCity(Guid valId) {
            try {
                CityLanguageViewModel vCity = new CityLanguageViewModel();
                if (Startup._IdCity != Guid.Empty) {
                    vCity.ListCity = new List<CityViewModel>();
                    vCity = await _vCityService.GetCityById(valId);
                    return View(vCity);
                }
                
            } catch (Exception) {

                return View();
            }
            return View();
        }
        #region Add
        [HttpPost]
        public async Task<IActionResult> Add() {
            CityLanguageViewModel vModel = new CityLanguageViewModel();
            try {
                List<Language> vLanguage = await _vLanguageSerivce.GetLanguage();
                List<Guid> vIdLanguage = vLanguage.Select(e => e.Id).ToList();

                if (Request.Form.Count != 0 && vIdLanguage.Count != 0) {
                    vModel.ListCity = new List<CityViewModel>();
                    FileViewModel vFile = new FileViewModel();
                    if (Request.Form.Files != null && Request.Form.Files.Count > 0) {
                        IFormFile file = Request.Form.Files[0];
                        byte[] data;
                        using (var br = new BinaryReader(file.OpenReadStream()))
                            data = br.ReadBytes((int)file.OpenReadStream().Length);
                        vFile.FileData = data;
                        vFile.NameFile = file.Name;
                        vFile.Size = file.Length;
                    };
                    for (int i = 0; i <= vIdLanguage.Count - 1; i++) {
                        vModel.ListCity.Add(new CityViewModel {
                            Name = Request.Form["Name"],
                            Icon = Request.Form["Icono"],
                            Temperature = !string.IsNullOrEmpty(Request.Form["Temperature"]) ? Convert.ToInt32(Request.Form["Temperature"]) : 0,
                            Altitude = !string.IsNullOrEmpty(Request.Form["Altitude"]) ? Convert.ToInt32(Request.Form["Altitude"]) : 0,
                            Population = !string.IsNullOrEmpty(Request.Form["Population"]) ? Convert.ToInt32(Request.Form["Population"]) : 0,
                            UserCreate = "Admin",//change for session user
                            DateCreate = DateTime.Now,
                            State = 1,
                            Photo = vFile,
                            IdLanguage = vIdLanguage.ElementAt(i),
                            Slogan = Request.Form["data-slogan" + i],
                            Description = Request.Form["data-description" + i],
                            Location = Request.Form["data-location" + i],
                            FarmingProduction = Request.Form["data-farming-production" + i],
                            DescriptionDistricts = Request.Form["data-description-districts" + i],
                        });

                    }
                    ClientResponseViewModel vResponse = await _vCityService.AddCity(vModel);
                    if (vResponse != null) {
                        if (vResponse.Result == "1") {
                            return Json(new { content = "1" });
                        } else if (vResponse.Result == "2") {
                            return Json(new { content = vResponse.Result });
                        } else if (vResponse.Result == "5") {
                            return Json(new { content = vResponse.Result });
                        } else if (vResponse.Result == "3" || vResponse.Result == "4") {
                            return Json(new { content = vResponse.Result });
                        }
                    }

                }
              
            } catch (Exception) {
                return Json(new { content ="6"});
            }

            return Json(new { content = "6" });
        }
        #endregion
        #region Update
        [HttpPost]
        public async Task<IActionResult> Edit() {
            CityLanguageViewModel vModel = new CityLanguageViewModel();
            try {
                

                if (Request.Form.Count != 0) {
                    vModel.ListCity = new List<CityViewModel>();
                    FileViewModel vFile = new FileViewModel();
                    if (Request.Form.Files != null && Request.Form.Files.Count > 0) {
                        IFormFile file = Request.Form.Files[0];
                        byte[] data;
                        using (var br = new BinaryReader(file.OpenReadStream()))
                            data = br.ReadBytes((int)file.OpenReadStream().Length);
                        vFile.FileData = data;
                        vFile.NameFile = file.Name;
                        vFile.Size = file.Length;
                    };
                    for (int i = 0; i <= 2; i++) {
                        vModel.ListCity.Add(new CityViewModel {
                            Name = Request.Form["Name"],
                            Icon = Request.Form["Icono"],
                            Temperature = !string.IsNullOrEmpty(Request.Form["Temperature"]) ? Convert.ToInt32(Request.Form["Temperature"]) : 0,
                            Altitude = !string.IsNullOrEmpty(Request.Form["Altitude"]) ? Convert.ToInt32(Request.Form["Altitude"]) : 0,
                            Population = !string.IsNullOrEmpty(Request.Form["Population"]) ? Convert.ToInt32(Request.Form["Population"]) : 0,
                            UserCreate = "Admin",//change for session user
                            DateCreate = DateTime.Now,
                            State = 1,
                            Photo = vFile,
                            IdLanguage = new Guid(Request.Form["id-language" + i]),
                            Slogan = Request.Form["data-slogan" + i],
                            Description = Request.Form["data-description" + i],
                            Location = Request.Form["data-location" + i],
                            FarmingProduction = Request.Form["data-farming-production" + i],
                            DescriptionDistricts = Request.Form["data-description-districts" + i],
                        });

                    }
                    ClientResponseViewModel vResponse = await _vCityService.AddCity(vModel);
                    if (vResponse != null) {
                        if (vResponse.Result == "1") {
                            return Json(new { content = "1" });
                        } else if (vResponse.Result == "2") {
                            return Json(new { content = vResponse.Result });
                        } else if (vResponse.Result == "5") {
                            return Json(new { content = vResponse.Result });
                        } else if (vResponse.Result == "3" || vResponse.Result == "4") {
                            return Json(new { content = vResponse.Result });
                        }
                    }

                }

            } catch (Exception) {
                return Json(new { content = "6" });
            }

            return Json(new { content = "6" });
        }
        [HttpPost]
        public async Task<IActionResult> ChangeState(string valId, string valState) {
            try {
                CityViewModel vCity = new CityViewModel();
                vCity.Id = new Guid(valId);
                vCity.State = Convert.ToInt32(valState);
                ClientResponseViewModel vResponse = await _vCityService.ChangeState(vCity);
                if (vResponse.Result == "1") {
                    return Json(new { content = "1", state = vCity.State });
                } else if (vResponse.Result == "3" || vResponse.Result == "4") {
                    return Json(new { content = vResponse.Result });
                }
            } catch (Exception) {
                return Json(new { content = "4", message = "Ha Ocurrido un error, no se puedo actualizar su estado" });
            }
            return Json(new { content = "4", message = "Ha Ocurrido un error, no se puedo actualizar su estado" });
        }
        #endregion
        #region Get
        public async Task<IActionResult> GetData() {
            List<CityViewModel> vCity = new List<CityViewModel>();
            vCity = await _vCityService.GetCity();
            return Json(new { data = vCity });
        }
        //public async Task<IActionResult> GetDataById(Guid valId) {
        //    try {
        //        CityLanguageViewModel vModel = new CityLanguageViewModel();
        //        vModel.ListCity = new List<CityViewModel>();
        //        vModel = await _vCityService.GetCityById(valId);
        //    } catch (Exception) {

        //        return Json(new { content = "4" });
        //    }
        //    return Json(new { content = "4" });
        //}
        [HttpPost]
        public IActionResult ValidId(Guid vId) {
            if (vId != Guid.Empty) {
                Startup._IdCity = vId;
                return Json(new { content= "true" });
            }

GoTourSiteAdmin/Controllers/UserController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoTourSiteAdmin.Models;
using GoTourSiteAdmin.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace GoTourSiteAdmin.Controllers
{
    public class UserController : Controller {
        private IUserService _vUserService;
        public IActionResult AllUser() {
            return View();
        }
        public IActionResult Details() {
            return View();
        }
        public UserController(IUserService vUserService) {
            _vUserService = vUserService;
        }
        #region Get
        public async Task<IActionResult> GetData() {
            List<UserViewModel> vList = new List<UserViewModel>();
            vList = await _vUserService.GetUser();
            return Json(new { data = vList });
        }
        public async Task<IActionResult> Detail() {
            UserViewModel vUser = new UserViewModel();
            var valId = Startup._IdUserPortal;
            if (valId != Guid.Empty) {
                vUser = await _vUserService.GetUserById(valId);
                Startup._IdUserPortal = Guid.Empty;
                return View("Details", vUser);
            }
            return RedirectToAction("Error", "Home");
        }
        public async Task<IActionResult> Edit() {
            UserViewModel vUser = new UserViewModel();
            var valId = Startup._IdUserPortal;
            if (valId != Guid.Empty) {
                vUser = await _vUserService.GetUserById(valId);
                return View("EditUser", vUser);
            }
            return RedirectToAction("Error", "Home");
        }
        [HttpPost]
        public IActionResult GetDataUser(Guid valId) {
            //var valId = new Guid(valId);
            if (valId != Guid.Empty) {
                Startup._IdUserPortal = valId;
                return Json(new { content = "True" });
            }
            return Json(new { content = "False" });
        }
        //public void UserViewModel() {
        //    Startup._vDataUser = Models.UserViewModel.ListUser;
        //}
        #endregion
        #region Update
        [HttpPost]
        public async Task<IActionResult> UpdateState(string valId, string valState) {
            try {
                UserViewModel vModel = new UserViewModel();
                vModel.Id = new Guid(valId);
                vModel.State = Convert.ToInt32(valState);
                ClientResponseViewModel vResponse = await _vUserService.UpdateState(vModel);
                if(vResponse.Result =="1") {
                    return Json( new { content="1" });
                }else if(vResponse.Result == "3" || vResponse.Result == "4") {
                    return Json( new { content = vResponse.Result });
                }
            } catch (Exception) {
                return Json(new { content = "5" });
            }
            return Json(new { content = "5" });
        }
        [HttpPost]
        public async Task<IActionResult> UpdateUser([FromBody] UserViewModel vModel) {
            try {
                ClientResponseViewModel vResponse = await _vUserService.Update(vModel);
                if(vResponse.Result == "1") {
                    return Json(new { content = vResponse.Result });
                } else if (vResponse.Result == "3" || vResponse.Result == "4") {
                    return Json(new { content= vResponse.Result });
                }
            } catch (Exception) {
                return Json(new { content = "5" });
            }
            return Json(new { content = "5" });
        }
        #endregion
        //[HttpPost]
        // public IActionResult EditUser(string valId) {
        //        UserViewModel ListUser = new UserViewModel();
        //        if(!string.IsNullOrEmpty(valId)) {
        //           ListUser = Startup._vDataUser.FirstOrDefault(i => i.Id.ToString() == valId);
        //        }
        //        return PartialView("_EditUser", ListUser);

        // }
        //[HttpPost]
        //public IActionResult Delete(string valId) {
        //    UserViewModel vUser = new UserViewModel();

        //    vUser = Startup._vDataUser.FirstOrDefault(i => i.Id.ToString() == valId);
        //    vUser.State = 1;

        //    return PartialView("_TableUser", vUser);
        //}

        //[HttpPost]
        //public IActionResult Edit([FromBody] UserViewModel vModel) {

        //    List<UserViewModel> vList = new List<UserViewModel>();
        //    UserViewModel vUser = new UserViewModel();
        //    if (vModel!= null) {
        //        vUser = Startup._vDataUser.FirstOrDefault(i => i.Id == vModel.Id);
        //    }
        //    vUser.Username = vModel.Username;
        //    vUser.FirstName = vModel.FirstName;
        //    vUser.FirstLastName = vModel.FirstLastName;
        //    vUser.Email = vModel.Email;
        //    vUser.Phone = vModel.Phone;
        //    vUser.UrlPhoto = vModel.UrlPhoto;
        //    vUser.State = 1;
        //    vList.Add(vUser);

        //    List<UserViewModel> vListNoEdit = Startup._vDataUser.Where(i => i.Id != vModel.Id).ToList();
        //    vList.AddRange(vListNoEdit);

        //    //foreach (var vItem in vUser.Where(w => w.Id.ToString() == vModel.Id.ToString())) {
        //    //    vItem.Username = vModel.Username;
        //    //    vItem.Phone = vModel.Phone;
        //    //    vItem.Email = vModel.Email;
        //    //}

        //    return PartialView("_TableUser", vList);
        //}

    }
}

GoTourSiteAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GoTourSiteAdmin</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
        <link href="~/lib/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/Jquery-steps/jquery.steps.css" rel="stylesheet" />
        <link href="~/fonts/Themify-icons/themify-icons.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>



    @RenderBody()



    <environment include="Development">
        <!--jquery-->
        <script src="~/lib/jquery/dist/jquery.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.0/dist/jquery.validate.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.0/dist/additional-methods.min.js"></script>
        <script src="~/js/jquery.validate-init.js"></script>
        <!--popper-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        @*<script src="~/lib/Jquery-steps/jquery.steps.min.js"></script>*@
        <script src="~/lib/Jquery-steps/jquery.steps.js"></script>
        @*<script src="~/lib/Jquery-steps/js.cookie.js"></script>*@
        <!--fontawesome-->
        <script defer src="~/lib/fontawesome/all.min.js"></script>
        <!--chartjs-->
        <script src="~/lib/chart/Chart.min.js"></script>
        <!--Sweetalert-->
        <script src="~/js/sweetalert2.all.min.js"></script>
        <!--Select4-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
        <!--Datatables-->
        <script src="~/lib/datatables/jquery.dataTables.min.js"></script>
        <script src="~/lib/datatables/dataTables.bootstrap4.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>


    
    @RenderSection("Scripts", required: false)
</body>
</html>

GoTourSiteAdmin/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-orange py-2 pl-md-4 pr-md-5">
    <button class="btn text-white border-right rounded-0" id="sidebar-toggler"><i class="fas fa-th"></i></button>
    <a class="navbar-brand font-weight-bold px-md-2" href="#">Administrador Global</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarGoTour">
        <span class="navbar-toggler-icon"><i class="fas fa-ellipsis-v"></i></span>
    </button>
    <div class="collapse navbar-collapse mr-auto pr-md-2" id="navbarGoTour">
        <ul class="navbar-nav ml-auto text-center">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle font-weight-bold" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="img-fluid" width="35" src="~/images/user.svg" alt="FotoPerfil"><span class="ml-2">Tania Camargo</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item font-weight-bold" href="#"><i class="mr-1 text-orange fas fa-cog"></i>&nbsp;Configuración</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item font-weight-bold" href="#"><i class="mr-1 text-orange fas fa-power-off"></i>&nbsp;Cerrar Sesión</a>

                </div>
            </li>
        </ul>
    </div>
</nav>

GoTourSiteAdmin/Views/Shared/_Sidebar.cshtml
<nav id="sidebar" class="sidebar bg-purple-dark px-md-4" role="navigation">
    <div class="sidebar-header text-center py-4">
        <img class="img-fluid rounded-circle border-lg border-purple-light" width="120" src="https://logopond.com/logos/de4305481984e56e5d5878bde95b632a.png" alt="Logo">
        <h5 class="font-weight-bold pt-3">
            Administrador
            Global
        </h5>
        <strong class="pt-4">AG</strong>
        <div class="line"></div>
    </div>
    <ul class="list-unstyled bg-purple-light rounded pb-4">
        <li>
            <a href="#submenu1" data-toggle="collapse" aria-expanded="false"><i class="fas fa-building"></i><span>Agencias</span> <i class="fas fa-chevron-right"></i></a>
            <ul class="collapse list-unstyled" id="submenu1">
                <li><a asp-area="" asp-controller="Agency" asp-action="AddAgency">Agregar</a></li>
                <li><a asp-area="" asp-controller="Agency" asp-action="EditAgency">Ver Todos</a></li>
            </ul>
        </li>
        <li><a asp-area="" asp-controller="User" asp-action="AllUser"><i class="fas fa-users"></i><span>Usuarios Web</span></a></li>
        <li>
            <a href="#submenu2" data-toggle="collapse" aria-expanded="false"><i class="fas fa-map-marked-alt"></i><span>Tours</span>  <i class="fas fa-chevron-right"></i></a>
            <ul class="collapse list-unstyled" id="submenu2">
                <li><a href="">Agregar</a></li>
                <li><a href="">Ver Todos</a></li>
            </ul>
        </li>
        <li>
            <a data-toggle="collapse" href="#submenu3" aria-expanded="false"><i class="fas fa-city"></i><span>Ciudad</span> <i class="fas fa-chevron-right"></i></a>
            <ul class="collapse list-unstyled" id="submenu3">
                <li><a asp-controller="City" asp-action="AddCity">Agregar</a></li>
                <li><a asp-controller="City" asp-action="All">Ver Todos</a></li>
            </ul>
        </li>
        <li><a asp-area="" asp-controller="UserPortal" asp-action="All"><i class="fas fa-user-edit"></i><span>Usuarios Portal</span></a></li>

    </ul>
</nav>